### ISSUE TITLE
Version with more keys on the side

### ISSUE THREAD

**Issue by burivuh26** [tewtham/dactyl-typesafe#10]
I saw at Reddit photos of first version of this keyboard with 28 keys at the side and 3-5 keys at the tumb. I didn't faint Stl-files for bigger versions of this keyboard at the GitHub.can you please add them? 
![1k2lzwhqzqz51](https://github.com/tewtham/dactyl-typesafe/assets/32369112/bb9dcdb8-da7c-417d-8016-4328b87b8bcc)

**Comment by tewtham** [comment]
Actually, these should already be available in an older commit [here](https://github.com/tewtham/dactyl-typesafe/tree/19f1c7c73a30299ffdcf735b0b7b016b3c7a2650/things/5x6). You can also find it from this tag https://github.com/tewtham/dactyl-typesafe/releases/tag/1.0.0
