### ISSUE TITLE
Design files

### ISSUE THREAD

**Issue by sickerin** [tewtham/dactyl-typesafe#5]
Hi @tewtham, what did you use to design this? Would you be able to share the design files? From my understanding, STL files are usually hard to make modification rights?

**Comment by tewtham** [comment]
Hey! sorry for the late reply. I used [fusion360](https://www.autodesk.com/products/fusion-360/personal) to do the design. My design files are quite messy, so I wasn't really planning on releasing them. You would probably find it pretty difficult to make modifications even with those 😅 .

I do have a fork of the [dactyl keyboard](https://github.com/tewtham/dactyl-keyboard) which only generates the key switch openings. This is what I've been basing all my designs on.
